<a href="https://colab.research.google.com/github/official-okello/DS_bootcamp_with_gomycode/blob/master/Python_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Write a Python program in the form of a function that takes two lists as parameters and returns True if the two lists have at least one common element, and False otherwise.

def common_elements(list1, list2):
    for element in list1:
        if element in list2:
            return True
    return False
list1 = [1, 2, 3, 4, 5]
list2 = [5, 6, 7, 8, 9]

print(common_elements(list1, list2))  # Output: True

True


In [ ]:
def common_elements(list1, list2):
    return bool(set(list1) & set(list2))  # Intersection of two sets

# Example Usage
list1 = [1, 2, 3, 4, 5]
list2 = [5, 6, 7, 8, 9]

print(common_elements(list1, list2))  # Output: True


True


In [ ]:
class Player:
  def __init__(self, name, hp=100):
    self.name = name
    self.hp = hp

  def take_damage(self,damage):
    self.hp = max(0, self.hp - damage)
    return self.hp

  def __str__(self):
    return f'{self.name} : {self.hp} HP'

player1 = Player('Julius')
player1.take_damage(40)
print(player1)

Julius : 60 HP


Numpy

In [ ]:
!pip install --upgrade pip

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 18.6 MB/s eta 0:00:00
  Attempting uninstall: pip
    Found existing installation: pip 24.1.2
    Uninstalling pip-24.1.2:
      Successfully uninstalled pip-24.1.2


In [ ]:
!pip install numpy

In [ ]:
import numpy as np

#ndarrays: n-dimensional arrays in numpy
array1 = np.array([1,2,3]) #1d array
# print(array1)

array2 = np.array([[1,2,3],[4,5,6]]) #2d array
# print(array2)

#reshaping an array
array3 = np.array([1,2,3,4,5,6])
array4 = array3.reshape(2,3)
# print(array4)

#flattening an array
array5 = np.array([[1,2,3,4],[5,6,7,8]])
array6 = np.reshape(array5, -1)
# print(array6)

#slicing an array
array7 = np.array([1,2,3,4,5,6])
array8 = array7[1:4]
# print(array8)

Elemnt-wise oparations

In [ ]:
array_1D = np.array([10, 11, 12, 13, 14])
print(array_1D[-1])
array_2D = np.array([[20, 30, 40, 50, 60], [43, 54, 65, 76, 87], [11, 22, 33, 44, 55]])
print(array_2D[-1][-1])
array_3D = np.array([[[1, 2, 3, 4, 5], [11, 21, 31, 41, 51]], [[11, 12, 13, 14, 15], [51, 52, 53, 54, 5]]])
print(array_3D[-1][-1][-1])

14
55
5


In [ ]:
array_a = np.array([7, 8, 9])
array_b = np.array([[1, 2, 3], [4, 5, 6]])

print(array_a * 2) #multiplication by a scalar
print(array_b + 2) #adding a scalar
print(array_a * array_b[1]) #multiplying by a row
print(array_b - array_a) #subtracting arrays, element_wise

[14 16 18]
[[3 4 5]
 [6 7 8]]
[28 40 54]
[[-6 -6 -6]
 [-3 -3 -3]]


Data types in np

In [ ]:
array_a = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.float16)
print("Floating-point array:", array_a)

array_a = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.complex64)
print("Complex array:", array_a)

array_a = np.array([[1, 2, 0], [4, 5, 6]], dtype=bool)
print("Boolean array:", array_a)

array_a = np.array([[1, 2, 3], [4, 5, 6]], dtype=str)
print("String array:", array_a)

Floating-point array: [[1. 2. 3.]
 [4. 5. 6.]]
Complex array: [[1.+0.j 2.+0.j 3.+0.j]
 [4.+0.j 5.+0.j 6.+0.j]]
Boolean array: [[ True  True False]
 [ True  True  True]]
String array: [['1' '2' '3']
 ['4' '5' '6']]


Slicing

In [ ]:
array_1D = np.array([10,11,12,13, 14])
array_2D = np.array([[20,30,40,50,60], [43,54,65,76,87], [11,22,33,44,55]])
array_3D = np.array([[[1,2,3,4,5], [11,21,31,41,51]], [[11,12,13,14,15], [51,52,53,54,5]]])

# Slice the first column of the 2-D array.
print(array_2D[:, 0])
# Slice the last two columns of the 2-nd row of the 2-D array
print(array_2D[1:, -2:])
# Slice the 2-nd row of the 2-D array excluding the last two columns
print(array_2D[1, :-2])

[20 43 11]
[[76 87]
 [44 55]]
[43 54 65]


Basic array generation functions

In [ ]:
array_empty = np.empty(shape=(2,3)) #empty array instanciation with random values generated
print(array_empty)

array_zeros = np.zeros(shape=(3,3))
print(array_zeros)

array_ones = np.ones((2,3))
print(array_ones)

array_full = np.full(shape=(2, 3), fill_value=2)
array_full_text = np.full(shape=(2, 3), fill_value='Sophie')

print(array_full)
print(array_full_text)

array_rng = np.arange(start=0, stop=30, step=2.5, dtype=np.float16)
array_rng_int = np.arange(start=0, stop=30, step=2.5, dtype=np.int32)

print(array_rng)
print(array_rng_int)

[[4.24399158e-314 1.27319747e-313 2.12199579e-313]
 [2.97079411e-313 3.81959242e-313 4.66839074e-313]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2 2]
 [2 2 2]]
[['Sophie' 'Sophie' 'Sophie']
 ['Sophie' 'Sophie' 'Sophie']]
[ 0.   2.5  5.   7.5 10.  12.5 15.  17.5 20.  22.5 25.  27.5]
[ 0  2  4  6  8 10 12 14 16 18 20 22]


NP statistical calculations

In [ ]:
#medians
array_1Dm = np.array([10, 11, 12, 13, 14])
print(np.median(array_1Dm))

array1_1Dm = np.array([10, 11, 12, 13, 14, 15])
print(np.median(array1_1Dm))

array2D = np.array([[2, 4, 6], [8, 10, 12], [14, 16, 18]])

# Median along the horizontal axis (axis=1)
median_horizontal = np.median(array2D, axis=1)
print("Median along horizontal axis:", median_horizontal)

# Median along the vertical axis (axis=0)
median_vertical = np.median(array2D, axis=0)
print("Median along vertical axis:", median_vertical)

# Median of the entire array
median_total = np.median(array2D)
print("Median of entire array:", median_total)

array1 = np.array([[1, 3],
                 [5, 7]])
# calculate the mean of the entire array
result1 = np.mean(array1)
print("Mean of entire Array:",result1)  # 4.0
# calculate the mean along vertical axis (axis=0)
result2 = np.mean(array1, axis=0)
print("Along Vertical Axis:",result2)
# calculate the mean along  (axis=1)
result3 = np.mean(array1, axis=1)
print("Along Horizontal Axis :",result3)


array1 = np.array([[2, 5, 9],
                 [3, 8, 11],
                 [4, 6, 7]])

# compute standard deviation along horizontal axis
result1 = np.std(array1, axis=1)
print("Standard deviation along horizontal axis:", result1)

# compute standard deviation along vertical axis
result2 = np.std(array1, axis=0)
print("Standard deviation  along vertical axis:", result2)

# compute standard deviation of entire array
result3 = np.std(array1)
print("Standard deviation of entire array:", result3)

array1 = np.array([1, 3, 5, 7, 9, 11, 13, 15, 17, 19])

# compute the 25th percentile of the array
result1 = np.percentile(array1, 25)
print("25th percentile:",result1)

# compute the 75th percentile of the array
result2 = np.percentile(array1, 75)
print("75th percentile:",result2)

array1 = np.array([2,6,9,15,17,22,65,1,62])

# find the minimum value of the array
min_val = np.min(array1)

# find the maximum value of the array
max_val = np.max(array1)

# print the results
print("Minimum value:", min_val)
print("Maximum value:", max_val)

matrix_A = np.array([[1, 0, 0, 3, 1], [3, 6, 6, 2, 9], [4, 5, 3, 8, 0]])
# Covariance matrix calculation
cov_matrix = np.cov(matrix_A)
print("Covariance matrix of matrix_A:\n", cov_matrix)

# Corelation matrix calculation
corr_matrix = np.corrcoef(matrix_A)
print("Correlation matrix of matrix_A:\n", corr_matrix)



12.0
12.5
Median along horizontal axis: [ 4. 10. 16.]
Median along vertical axis: [ 8. 10. 12.]
Median of entire array: 10.0
Mean of entire Array: 4.0
Along Vertical Axis: [3. 5.]
Along Horizontal Axis : [2. 6.]
Standard deviation along horizontal axis: [2.86744176 3.29983165 1.24721913]
Standard deviation  along vertical axis: [0.81649658 1.24721913 1.63299316]
Standard deviation of entire array: 2.7666443551086073
25th percentile: 5.5
75th percentile: 14.5
Minimum value: 1
Maximum value: 65


FizzBUzz

In [ ]:
for i in range(50):
  if (i+1) % 3 == 0 and (i+1) % 5 == 0:
    print("FizzBuzz")
  elif (i+1) % 3 == 0:
    print("Fizz")
  elif (i+1) % 5 == 0:
    print("Buzz")
  else:
    print(i+1)

1
2
Fizz
4
Buzz
Fizz
7
8
Fizz
Buzz
11
Fizz
13
14
FizzBuzz
16
17
Fizz
19
Buzz
Fizz
22
23
Fizz
Buzz
26
Fizz
28
29
FizzBuzz
31
32
Fizz
34
Buzz
Fizz
37
38
Fizz
Buzz
41
Fizz
43
44
FizzBuzz
46
47
Fizz
49
Buzz


In [ ]:
def fizz_buzz():
  for i in range(1,51):
    if i % 3 == 0 and i % 5 == 0:
      print("FizzBuzz")
    elif i % 3 == 0:
      print("Fizz")
    elif i % 5 == 0:
      print("Buzz")
    else:
      print(i)

fizz_buzz()

1
2
Fizz
4
Buzz
Fizz
7
8
Fizz
Buzz
11
Fizz
13
14
FizzBuzz
16
17
Fizz
19
Buzz
Fizz
22
23
Fizz
Buzz
26
Fizz
28
29
FizzBuzz
31
32
Fizz
34
Buzz
Fizz
37
38
Fizz
Buzz
41
Fizz
43
44
FizzBuzz
46
47
Fizz
49
Buzz


Prime

In [ ]:
# Store employee salaries in a list.
salaries = [15000, 13000, 20000, 10000, 18000, 20000, 35000, 23000, 17000, 16000]
# Store performance ratings in another list (aligned with the salary list).
ratings = [2, 3, 1, 3, 2, 4, 5, 2, 3, 5, 4]
# Use a for loop to iterate through the employees and calculate their bonuses.
for salary in salaries:
  if ratings[salaries.index(salary)] == 5:
    bonus = salary * 0.2
  elif ratings[salaries.index(salary)] == 4:
    bonus = salary * 0.1
  elif ratings[salaries.index(salary)] == 3:
    bonus = salary * 0.05
  else:
    bonus = 0
  print(f'Employee with Salary ${salary} got rating {ratings[salaries.index(salary)]} and ${bonus} in bonus')
  # print('Employee with Salary ${} got rating {} and ${} in bonus'. format(str(salary), str(ratings[salaries.index(salary)]), str(bonus)))
  # print('Employee with Salary $', salary, 'got rating', ratings[salaries.index(salary)], 'and $' ,bonus, 'in bonus')
# Print each employee’s salary, rating, and calculated bonus.

Employee with Salary $15000 got rating 2 and $0 in bonus
Employee with Salary $13000 got rating 3 and $650.0 in bonus
Employee with Salary $20000 got rating 1 and $0 in bonus
Employee with Salary $10000 got rating 3 and $500.0 in bonus
Employee with Salary $18000 got rating 2 and $0 in bonus
Employee with Salary $20000 got rating 1 and $0 in bonus
Employee with Salary $35000 got rating 5 and $7000.0 in bonus
Employee with Salary $23000 got rating 2 and $0 in bonus
Employee with Salary $17000 got rating 3 and $850.0 in bonus
Employee with Salary $16000 got rating 5 and $3200.0 in bonus


In [ ]:
def calculate_bonus(salary, rating):
  if rating == 5:
    bonus = salary * 0.2
  elif rating == 4:
    bonus = salary * 0.1
  elif rating == 3:
    bonus = salary * 0.05
  else:
    bonus = 0
  return bonus

salaries = [15000, 13000, 20000, 10000, 18000, 20000, 35000, 23000, 17000, 16000]
ratings = [2, 3, 1, 3, 2, 4, 5, 2, 3, 5, 4]

for i in range(len(salaries)):
  bonus = calculate_bonus(salaries[i], ratings[i])
  print(f'Employee with Salary ${salaries[i]} got rating {ratings[i]} and ${bonus} in bonus')

Employee with Salary $15000 got rating 2 and $0 in bonus
Employee with Salary $13000 got rating 3 and $650.0 in bonus
Employee with Salary $20000 got rating 1 and $0 in bonus
Employee with Salary $10000 got rating 3 and $500.0 in bonus
Employee with Salary $18000 got rating 2 and $0 in bonus
Employee with Salary $20000 got rating 4 and $2000.0 in bonus
Employee with Salary $35000 got rating 5 and $7000.0 in bonus
Employee with Salary $23000 got rating 2 and $0 in bonus
Employee with Salary $17000 got rating 3 and $850.0 in bonus
Employee with Salary $16000 got rating 5 and $3200.0 in bonus


In [ ]:
salaries = [15000, 13000, 20000, 10000, 18000, 20000, 35000, 23000, 17000, 16000]
ratings = [2, 3, 1, 3, 2, 4, 5, 2, 3, 5, 4]

for i in range(len(salaries)):
  if ratings[i] == 5:
    bonus = salaries[i] * 0.2
  elif ratings[i] == 4:
    bonus = salaries[i] * 0.1
  elif ratings[i] == 3:
    bonus = salaries[i] * 0.05
  else:
    bonus = 0
  # print(f'Employee with Salary ${salaries[i]} got rating {ratings[i]} and ${bonus} in bonus')
  print('Employee with Salary $', salaries[i], 'got rating', ratings[i], 'and $' ,bonus, 'in bonus')

Employee with Salary $ 15000 got rating 2 and $ 0 in bonus
Employee with Salary $ 13000 got rating 3 and $ 650.0 in bonus
Employee with Salary $ 20000 got rating 1 and $ 0 in bonus
Employee with Salary $ 10000 got rating 3 and $ 500.0 in bonus
Employee with Salary $ 18000 got rating 2 and $ 0 in bonus
Employee with Salary $ 20000 got rating 4 and $ 2000.0 in bonus
Employee with Salary $ 35000 got rating 5 and $ 7000.0 in bonus
Employee with Salary $ 23000 got rating 2 and $ 0 in bonus
Employee with Salary $ 17000 got rating 3 and $ 850.0 in bonus
Employee with Salary $ 16000 got rating 5 and $ 3200.0 in bonus


In [ ]:
employees = [
{
    "name": "Julius",
    "salary": 15000,
    "rating": 2
},
{
    "name" : "Sophie",
    "salary" : 13000,
    "rating" : 3
},
{
    "name" : "Peter",
    "salary" : 20000,
    "rating" : 1
},
{
    "name" : "John",
    "salary" : 10000,
    "rating" : 3
},
{
    "name" : "Mary",
    "salary" : 18000,
    "rating" : 2
},
{
    "name" : "David",
    "salary" : 20000,
    "rating" : 4
},
{
    "name" : "Emily",
    "salary" : 35000,
    "rating" : 5
}
]

for employee in employees:
  if employee['rating'] == 5:
    bonus = employee['salary'] * 0.2
  elif employee['rating'] == 4:
    bonus = employee['salary'] * 0.1
  elif employee['rating'] == 3:
    bonus = employee['salary'] * 0.05
  else:
    bonus = 0
  print(f'Employee {employee["name"]} got a rating of {employee["rating"]} and has a bonus of ${bonus}')

Employee Julius got a rating of 2 and has a bonus of $0
Employee Sophie got a rating of 3 and has a bonus of $650.0
Employee Peter got a rating of 1 and has a bonus of $0
Employee John got a rating of 3 and has a bonus of $500.0
Employee Mary got a rating of 2 and has a bonus of $0
Employee David got a rating of 4 and has a bonus of $2000.0
Employee Emily got a rating of 5 and has a bonus of $7000.0


In [ ]:
ratings = (2, 3, 1, 3, 2, 4, 5, 2, 3, 5, 4)

for i in range(len(ratings)):
  salary = input('Please enter your salary or exit to exit: ')
  if salary == 'exit':
    break
  salary = int(salary)
  if ratings[i] == 5:
    bonus = salary * 0.2
  elif ratings[i] == 4:
    bonus = salary * 0.1
  elif ratings[i] == 3:
    bonus = salary * 0.05
  else:
    bonus = 0
  quit()
  # print(f'Employee with Salary ${salaries[i]} got rating {ratings[i]} and ${bonus} in bonus')
  print('Employee with Salary $', salary, 'got rating', ratings[i], 'and $' ,bonus, 'in bonus')

Please enter your salary or exit to exit: 34555
Employee with Salary $ 34555 got rating 2 and $ 0 in bonus
Please enter your salary or exit to exit: 50000
Employee with Salary $ 50000 got rating 3 and $ 2500.0 in bonus
Please enter your salary or exit to exit: exit


In [ ]:
#calculate prime numbers

def is_prime(num):
  if num < 2:
    return False
  if num == 2 or num == 3:
    return True
  else:
    for i in range(2, int(num ** 0.5) + 1):
      if num % i == 0:
        return False
  return True

for i in range(1, 51):
  if is_prime(i):
    print(i)

2
3
5
7
11
13
17
19
23
29
31
37
41
43
47


In [ ]:
def fizz_buzz():
  if (i+1) % 3 == 0 and (i+1) % 5 == 0:
    return "FizzBuzz"
  elif (i+1) % 3 == 0:
    return "Fizz"
  elif (i+1) % 5 == 0:
    return "Buzz"
  else:
    return i+1

for i in range(50):
  print(fizz_buzz())

1
2
Fizz
4
Buzz
Fizz
7
8
Fizz
Buzz
11
Fizz
13
14
FizzBuzz
16
17
Fizz
19
Buzz
Fizz
22
23
Fizz
Buzz
26
Fizz
28
29
FizzBuzz
31
32
Fizz
34
Buzz
Fizz
37
38
Fizz
Buzz
41
Fizz
43
44
FizzBuzz
46
47
Fizz
49
Buzz


In [ ]:
def total_fare(distance):
  base_fare = 200
  additional_fare = ((distance * 1000)//140)*25
  return base_fare + additional_fare

print(total_fare(10))

1975


In [ ]:
# A particular cell phone plan includes 20 minutes of air time and 20 text messages
# for Ksh. 50.00 a month. Each additional minute of air time costs Ksh. 3.00,
# while additional text messages cost Ksh. 2.00 each.
# The entire bill (including the 999 charge) is subject to 16 percent VAT tax.
# Write a program that reads the number of minutes and text messages used in a month from the user.
# Display the base charge, additional minutes charge (if any),
# additional text message charge (if any), tax and total bill amount.
# Only display the additional minute and text message charges if the user incurred costs in these categories.
# Ensure that all of the charges are displayed using 2 decimal places.
#

def additional_charges(minutes, messages):
  extra_charge = 0
  if minutes > 20:
    extra_charge +=  ((minutes - 20) * 3)
  if messages > 20:
    extra_charge += ((messages - 20) * 2)
  return extra_charge

def calculate_tax(bill):
  return bill * 0.16

def total_bill_amount(bill, tax):
  return bill + tax

def main():
  minutes = int(input('Please enter the number of minutes: '))
  messages = int(input('Please enter the number of messages: '))
  base_charge = 50
  additional_charge = additional_charges(minutes, messages)
  tax = calculate_tax(base_charge + additional_charge)
  total_bill = total_bill_amount(base_charge + additional_charge, tax)

  print(f'Base charge: Ksh {base_charge:.2f}')
  if additional_charge > 0:
    print(f'Additional charge: Ksh {additional_charge:.2f}')
  print(f'Tax: Ksh {tax:.2f}')
  print(f'Total bill: Ksh {total_bill:.2f}')

while True:
  main()
  quit = input('Do you want to quit? (y/n): ').lower()
  if quit == 'y':
    break

Please enter the number of minutes: 21
Please enter the number of messages: 20
Base charge: Ksh 50.00
Additional charge: Ksh 3.00
Tax: Ksh 8.48
Total bill: Ksh 61.48
Do you want to quit? (y/n): y


In [ ]:
# Create a text file and write your name and age into it.
# Read the file and print its contents.
# Append a new line to the file with your favorite hobby.

with open("example1.txt", "w") as example_file:
  example_file.write("Julius")
  example_file.write("25")

with open("example1.txt", "r") as example_file:
  print(example_file.read())

with open('example1.txt', "a") as example_file:
  example_file.write("Coding")

Julius25


In [ ]:
import csv

data = [
    ['Name', 'Age', 'City'],
    ['Alice', 30, 'New York'],
    ['Bob', 25, 'London'],
    ['Charlie', 35, 'Paris']
]

with open('records.csv', 'w', newline='') as csvfile:
    writer = csv.writer(csvfile)
    writer.writerows(data)


In [ ]:
import numpy as np

data1 = np.genfromtxt('records.csv', delimiter=',', dtype=str)
print(data1)

[['Name' 'Age' 'City']
 ['Alice' '30' 'New York']
 ['Bob' '25' 'London']
 ['Charlie' '35' 'Paris']]


In [ ]:
trials = 0
correct_pin = lambda pin: pin == '1234'

while trials < 3:
  pin = input("Enter 4-digit pin: ")

  if len(pin) != 4:
    print("Invalid pin, should be 4 characters long")
    continue

  if correct_pin(pin):
    print('✅ Access Granted!')
    break
  else:
    print(f'You have {2-trials} attempts remaining')
    trials += 1

  if trials == 3:
    print('🚫 Account Locked!')

Enter 4-digit pin: 1243
You have 2 attempts remaining
Enter 4-digit pin: 1234
✅ Access Granted!


In [ ]:
trials = 0
correct_pin = '1234'

while trials < 3:
  pin = input("Enter 4-digit pin: ")

  if len(pin) != 4:
    print("Invalid pin, should be 4 characters long")
    continue

  if pin == correct_pin:
    print('✅ Access Granted!')
    break

  else:
    print(f'You have {2-trials} attempts remaining')
    trials += 1

  if trials == 3:
    print('🚫 Account Locked!')

Enter 4-digit pin: 5767
Enter 4-digit pin: 2453
Enter 4-digit pin: 1234
Access Granted


In [ ]:
#comments
# syntax
# print("hello")
# variables
# phone_number = "123"
# print(name)
# data types
# int, float, str, boolean(True or False, 1,0)
# casting
# phone_number = int(phone_number)
# salary = int(input("Enter salo: "))
# print(salary * 3)
# print(type(phone_number))

# strings - indexing, slicing, methods
'hello', "hello", '''hello''', """hello"""
hey = 'HeLLo'
# lower()
# upper()

# print(hey[:])
# numbers - int,float,complex,math
# 123, 1, -1000, 1090, 2.3, 9.78678, 3i, 5i,
# print(len(str(123)))
# booleans
# True, False, 1, 0
# hey = ''
# print(len(hey))
# print(bool(''))
# operators
# + - ^ / * += -= and or not in
# trials = "123"
# print("2" not in trials)
# trials /= 2 #trials = trials / 1
# print(trials)
# lists
list1 = [1,23, 345, "hello", 'hello']
# list1.remove("hello")
# print(list1)
# print(list1.count("hello"))
# methods= append, insert, remove, pop, clear, index, count, sort, reverse, copy
# tuples
tuple1 = (list1,)
# methods = count, index
# print(tuple1) #immutable
# print(tuple1
# sets
# set1 = {1,1,2,3,3}
# set2 = {1,2,4,5,6,7}
# print(set1.union(set2))
# methods = union, intersection, difference, symmetric_difference, add, remove, pop, clear, copy
# dictionaries
# key, value pairs
dict1 = {
    'name': "billy",
    'course': "DS",
    'age': 20
}
# for key,value in dict1.items():
#   print(f'{key}: {value}')
# methods = get, keys, values, items, update, pop, popitem, clear, copy
# print(dict1.keys())
# print(dict1.items())
# if else

# y = "YES"
# if y == "yes".upper():
#   print("Yes")
# else:
#   print("No")

# loops
# while
# for
# functions
# lambdas

Yes


In [ ]:
x = 0
while x <= 10:
  if x == 5:
    x += 1
    continue
  print(x)
  x += 1

0
1
2
3
4
6
7
8
9
10


In [ ]:
import requests

# Replace 'YOUR_API_KEY' with your actual WeatherAPI key
api_key = "YOUR_ACTUAL_API_KEY"
url = f"https://api.weatherapi.com/v1/current.json?key={api_key}&q=Nairobi"

response = requests.get(url)

# Check if the request was successful (status code 200)
if response.status_code == 200:
  print(response.json())  # Returns weather data for Nairobi
else:
  print(f"Error: {response.status_code}")
  print(response.text)  # Print the error message from the API

Error: 403
{"error":{"code":2008,"message":"API key has been disabled."}}


Request library

In [ ]:
!pip install requests

In [ ]:
#GET Method
import requests

api_url = "https://jsonplaceholder.typicode.com/todos/1"
response = requests.get(api_url)
for key, value in response.headers.items():
  print(f"{key}: {value}")
# response.json()

Date: Sun, 09 Mar 2025 13:37:12 GMT
Content-Type: application/json; charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
Content-Encoding: zstd
Cf-Ray: 91daf735ec5430e1-SEA
Report-To: {"group":"heroku-nel","max_age":3600,"endpoints":[{"url":"https://nel.heroku.com/reports?ts=1735209657&sid=e11707d5-02a7-43ef-b45e-2cf4d2036f7d&s=hwYd9KoHJhxQAvfZLDbwdU76vYjwXOnbJ93lb8EqTyM%3D"}]}
Reporting-Endpoints: heroku-nel=https://nel.heroku.com/reports?ts=1735209657&sid=e11707d5-02a7-43ef-b45e-2cf4d2036f7d&s=hwYd9KoHJhxQAvfZLDbwdU76vYjwXOnbJ93lb8EqTyM%3D
Nel: {"report_to":"heroku-nel","max_age":3600,"success_fraction":0.005,"failure_fraction":0.05,"response_headers":["Via"]}
X-Powered-By: Express
X-Ratelimit-Limit: 1000
X-Ratelimit-Remaining: 999
X-Ratelimit-Reset: 1735209713
Vary: Origin, Accept-Encoding
Access-Control-Allow-Credentials: true
Cache-Control: max-age=43200
Pragma: no-cache
Expires: -1
X-Content-Type-Options: nosniff
Etag: W/"53-hfEnumeNh6YirfjyjaujcOPPT+s"
Via: 1.1 vegur


In [ ]:
print(response.status_code)

200


In [ ]:
#POST Method
data = {
    "userId": 1,
    "title": "Buy milk",
    "completed": False
}

# Define the API endpoint
api_url = "https://jsonplaceholder.typicode.com/todos"

# Send a POST request
response = requests.post(api_url, json=data)

# Print the response JSON
print(response.json())

{'userId': 1, 'title': 'Buy milk', 'completed': False, 'id': 201}


In [ ]:
#PUT Method

todo = {"userId": 1, "title": "Wash car", "completed": True}
response = requests.put(api_url, json=todo)
response.json()

{}

In [ ]:
#DELETE Method

#Specify the API URL for the resource you want to delete
api_url = "https://jsonplaceholder.typicode.com/todos/10"

# Send a DELETE request
response = requests.delete(api_url)

# Optional: Retrieve any returned data as JSON
deleted_response = response.json()
print(deleted_response)

# Check and print the HTTP status code of the response
print(response.status_code)

{}
200


Web scraping with python

In [ ]:
#to download a webpage from google.com
import requests as re
page = re.get("https://www.google.com")
print(page.content)

b'<!doctype html><html itemscope="" itemtype="http://schema.org/WebPage" lang="en"><head><meta content="Search the world\'s information, including webpages, images, videos and more. Google has many special features to help you find exactly what you\'re looking for." name="description"><meta content="noodp, " name="robots"><meta content="text/html; charset=UTF-8" http-equiv="Content-Type"><meta content="/images/branding/googleg/1x/googleg_standard_color_128dp.png" itemprop="image"><title>Google</title><script nonce="G0lgNhs1qbCU7VAx4bdCeg">(function(){var _g={kEI:\'eKLOZ9aVOcut5NoP-N_4kAY\',kEXPI:\'0,202791,1153989,2343540,1064,538661,2872,2891,73050,16105,344796,290044,5241623,131,8834893,78,3,1,4,3,2,2,23933874,4043710,25228681,123104,884,14280,8182,5933,4559,18354,39594,2664,3430,3319,23879,9138,4600,328,6225,10417,23894,16265,12879,710,1346,13702,8211,1959,1327,4134,21306,33,9041,17667,10666,10904,10441,8340,41,6135,7504,1,4922,1819,4106,21109,1241,3,2749,950,2150,4607,7,5773,4311,2

In [ ]:
#using BeautifulSoup library
from bs4 import BeautifulSoup
soup = BeautifulSoup(page.content, 'html.parser')
print(soup.prettify())

<!DOCTYPE html>
<html itemscope="" itemtype="http://schema.org/WebPage" lang="en">
 <head>
  <meta content="Search the world's information, including webpages, images, videos and more. Google has many special features to help you find exactly what you're looking for." name="description"/>
  <meta content="noodp, " name="robots"/>
  <meta content="text/html; charset=utf-8" http-equiv="Content-Type"/>
  <meta content="/images/branding/googleg/1x/googleg_standard_color_128dp.png" itemprop="image"/>
  <title>
   Google
  </title>
  <script nonce="G0lgNhs1qbCU7VAx4bdCeg">
   (function(){var _g={kEI:'eKLOZ9aVOcut5NoP-N_4kAY',kEXPI:'0,202791,1153989,2343540,1064,538661,2872,2891,73050,16105,344796,290044,5241623,131,8834893,78,3,1,4,3,2,2,23933874,4043710,25228681,123104,884,14280,8182,5933,4559,18354,39594,2664,3430,3319,23879,9138,4600,328,6225,10417,23894,16265,12879,710,1346,13702,8211,1959,1327,4134,21306,33,9041,17667,10666,10904,10441,8340,41,6135,7504,1,4922,1819,4106,21109,1241,3,274

In [ ]:
print(list(soup.children))

['html', <html itemscope="" itemtype="http://schema.org/WebPage" lang="en"><head><meta content="Search the world's information, including webpages, images, videos and more. Google has many special features to help you find exactly what you're looking for." name="description"/><meta content="noodp, " name="robots"/><meta content="text/html; charset=utf-8" http-equiv="Content-Type"/><meta content="/images/branding/googleg/1x/googleg_standard_color_128dp.png" itemprop="image"/><title>Google</title><script nonce="G0lgNhs1qbCU7VAx4bdCeg">(function(){var _g={kEI:'eKLOZ9aVOcut5NoP-N_4kAY',kEXPI:'0,202791,1153989,2343540,1064,538661,2872,2891,73050,16105,344796,290044,5241623,131,8834893,78,3,1,4,3,2,2,23933874,4043710,25228681,123104,884,14280,8182,5933,4559,18354,39594,2664,3430,3319,23879,9138,4600,328,6225,10417,23894,16265,12879,710,1346,13702,8211,1959,1327,4134,21306,33,9041,17667,10666,10904,10441,8340,41,6135,7504,1,4922,1819,4106,21109,1241,3,2749,950,2150,4607,7,5773,4311,2063,8657,

Analysing weather forecast webpage

In [ ]:
#downloading the webpage
import requests as re
from bs4 import BeautifulSoup
import pandas as pd

page = re.get("https://forecast.weather.gov/MapClick.php?lat=37.7772&lon=-122.4168")
soup = BeautifulSoup(page.content, 'html.parser')
seven_day = soup.find(id="seven-day-forecast")
forecast_items = seven_day.find_all(class_="tombstone-container")
tonight = forecast_items[0]
print(tonight.prettify())

#extract specifics
period = tonight.find(class_="period-name").get_text()
short_desc = tonight.find(class_="short-desc").get_text()
temp = tonight.find(class_="temp").get_text()
print(period)
print(short_desc)
print(temp)

img = tonight.find("img")
desc = img['title']
print(desc)

#extracting all info
period_tags = seven_day.select(".tombstone-container .period-name")
periods = [pt.get_text() for pt in period_tags]
short_descs = [sd.get_text() for sd in seven_day.select(".tombstone-container .short-desc")]
temps = [t.get_text() for t in seven_day.select(".tombstone-container .temp")]
descs = [d["title"] for d in seven_day.select(".tombstone-container img")]
print(periods)
print(short_descs)
print(temps)
print(descs)

#combining data into dataframe
weather = pd.DataFrame({
"period": periods,
"short_desc": short_descs,
"temp": temps,
"desc": descs
})

weather.to_csv('weather.csv', index=False)
weather.head()

<div class="tombstone-container">
 <p class="period-name">
  Overnight
 </p>
 <p>
  <img alt="Overnight: Mostly cloudy, with a low around 46. Calm wind. " class="forecast-icon" src="newimages/medium/nbkn.png" title="Overnight: Mostly cloudy, with a low around 46. Calm wind. "/>
 </p>
 <p class="temp temp-low">
  Low: 46 °F
 </p>
 <p class="short-desc">
  Mostly Cloudy
 </p>
</div>

Overnight
Mostly Cloudy
Low: 46 °F
Overnight: Mostly cloudy, with a low around 46. Calm wind. 
['Overnight', 'Monday', 'Monday Night', 'Tuesday', 'Tuesday Night', 'Wednesday', 'Wednesday Night', 'Thursday', 'Thursday Night']
['Mostly Cloudy', 'Partly Sunny', 'Partly Cloudy', 'Sunny', 'Chance Rain', 'Rain', 'Rain', 'Rain', 'Chance Rain']
['Low: 46 °F', 'High: 65 °F', 'Low: 47 °F', 'High: 62 °F', 'Low: 51 °F', 'High: 58 °F', 'Low: 46 °F', 'High: 56 °F', 'Low: 46 °F']
['Overnight: Mostly cloudy, with a low around 46. Calm wind. ', 'Monday: Partly sunny, with a high near 65. Calm wind becoming west 5 to 9 mph in

period     short_desc         temp  \
0      Overnight  Mostly Cloudy   Low: 46 °F   
1         Monday   Partly Sunny  High: 65 °F   
2   Monday Night  Partly Cloudy   Low: 47 °F   
3        Tuesday          Sunny  High: 62 °F   
4  Tuesday Night    Chance Rain   Low: 51 °F   

                                                desc  
0  Overnight: Mostly cloudy, with a low around 46...  
1  Monday: Partly sunny, with a high near 65. Cal...  
2  Monday Night: Partly cloudy, with a low around...  
3  Tuesday: Sunny, with a high near 62. Calm wind...  
4  Tuesday Night: A 40 percent chance of rain aft...

Binary Gap

In [ ]:
import requests as re
from bs4 import BeautifulSoup

In [ ]:
page = re.get('https://en.m.wikipedia.org/wiki/David_Lynch')
soup =  BeautifulSoup(page.text, 'html.parser')

links = soup.find_all('a')
for link in links:
  print(link.get('href'))

#
/wiki/Main_Page
/wiki/Special:Random
/wiki/Special:Nearby
/w/index.php?title=Special:UserLogin&returnto=David+Lynch
/w/index.php?title=Special:MobileOptions&returnto=David+Lynch
https://donate.wikimedia.org/?wmf_source=donate&wmf_medium=sidebar&wmf_campaign=en.wikipedia.org&uselang=en&wmf_key=minerva
/wiki/Wikipedia:About
/wiki/Wikipedia:General_disclaimer
/wiki/Main_Page
/wiki/David_Lynch
/wiki/Talk:David_Lynch
#p-lang
/w/index.php?title=Special:UserLogin&returnto=David+Lynch
/w/index.php?title=David_Lynch&action=edit
/wiki/David_Lynch_(disambiguation)
#cite_note-6
/wiki/David_Lynch_filmography
/wiki/Surrealist
/wiki/Experimental_film
/wiki/List_of_accolades_received_by_David_Lynch
/wiki/Golden_Lion_for_Lifetime_Achievement
/wiki/Venice_Film_Festival
/wiki/Honorary_Academy_Award
/wiki/File:David_Lynch_(1990).jpg
/wiki/Missoula,_Montana
/wiki/Hollywood_Forever_Cemetery
/wiki/Pennsylvania_Academy_of_the_Fine_Arts
/wiki/David_Lynch_filmography
/wiki/David_Lynch_discography
/wiki/David_

In [ ]:
#find binary gap
import re

def solution(N):
  bin = f'{N:b}'
  bin_gaps = re.findall(r'1(0+)1', bin)

  return max((len(gap) for gap in bin_gaps), default = 0)


print(solution(9))

def solution(N):
  return len(max(f'{N:b}'.strip('0').split('1')))

print(solution(1041))

2
5


In [ ]:
def solution(A):
  list1 = []
  for i in

LIBRARY MS

In [ ]:
class Book:
  def __init__(self, title:str, author:str, ISBN:str, available=True):
    self.title = title
    self.author = author
    self.ISBN = ISBN
    self.available = available

  def borrow_book(self):
    if self.available:
      self.available = False
      return True
    else:
      return False

  def return_book(self):
    self.available = True

  def get_info(self):
    return f'📖{self.title} by {self.author} | ISBN: {self.ISBN} | Available: {self.available}'

class Library:
  def __init__(self):
    self.books = {}

  def find_book(self, ISBN):
    return self.books.get(ISBN, None)

  def add_book(self, book):
    if book.ISBN in self.books:
      print(f"⚠️ Book with ISBN {book.ISBN} already exists!")
    else:
      self.books[book.ISBN] = book
      print(f"✅ Book '{book.title}' added to the library!")

  def borrow_book(self, ISBN):
    book = self.find_book(ISBN)
    if book and book.borrow_book():
      print(f"✅ Book '{book.title}' borrowed successfully!")
    else:
      print(f"❌ Book with ISBN {ISBN} is not available for borrowing.")

  def return_book(self, ISBN):
    book = self.find_book(ISBN)
    if book:
      book.return_book()
      print(f"✅ Book '{book.title}' returned successfully!")
    else:
      print(f"❌ Book with ISBN {ISBN} not found in the library.")

  def list_books(self):
    if not self.books:
      print("No books in the library.")
    for book in self.books.values():
      print(book.get_info())

def register_user(name, password):
  users = {}
  if name in users:
    print("Username already exists. Please choose a different username.")
  users[name] = password
  print(f"✅ User '{name}' registered successfully!")

#I will impliment auth into the system polepole, no rush nigga
def display_menu():
    print("\nMozart Library Management System")
    print("1. Add Book")
    print("2. Borrow Book")
    print("3. Return Book")
    print("4. List Books")
    print("5. Find Book")
    print("6. Quit")

#I will store books in a csv or json format later on
def store_books():
  pass


mozart_library = Library()

while True:
  display_menu()
  choice = input("Enter your choice (1-6): ")

  if choice not in ['1', '2', '3', '4', '5', '6']:
    print("Invalid choice. Please try again with choice between 1-6.")
    continue

  if choice == '6':
    print("Thank you for using Mozart Library Management System. Goodbye!")
    break
  if choice == '1':
    title = input("Enter book title: ")
    author = input("Enter author name: ")
    ISBN = input("Enter ISBN: ")
    new_book = Book(title, author, ISBN)

    mozart_library.add_book(new_book)

  if choice == '2':
    ISBN = input("Enter ISBN of the book to borrow: ")
    mozart_library.borrow_book(ISBN)

  if choice == '3':
    ISBN = input("Enter ISBN of the book to return: ")
    mozart_library.return_book(ISBN)

  if choice == '4':
    mozart_library.list_books()

  if choice == '5':
    ISBN = input("Enter ISBN of the book to find: ")
    book = mozart_library.find_book(ISBN)
    if book:
      print(book.get_info())


Mozart Library Management System
1. Add Book
2. Borrow Book
3. Return Book
4. List Books
5. Find Book
6. Quit
Enter your choice (1-6): 4
No books in the library.

Mozart Library Management System
1. Add Book
2. Borrow Book
3. Return Book
4. List Books
5. Find Book
6. Quit
Enter your choice (1-6): 1
Enter book title: Maths
Enter author name: Patel
Enter ISBN: 1234
✅ Book 'Maths' added to the library!

Mozart Library Management System
1. Add Book
2. Borrow Book
3. Return Book
4. List Books
5. Find Book
6. Quit
Enter your choice (1-6): 4
📖Maths by Patel | ISBN: 1234 | Available: True

Mozart Library Management System
1. Add Book
2. Borrow Book
3. Return Book
4. List Books
5. Find Book
6. Quit
Enter your choice (1-6): 2
Enter ISBN of the book to borrow: 1234
✅ Book 'Maths' borrowed successfully!

Mozart Library Management System
1. Add Book
2. Borrow Book
3. Return Book
4. List Books
5. Find Book
6. Quit
Enter your choice (1-6): 6
Thank you for using Mozart Library Management System. Good

Data Exploration with Pandas

In [ ]:
import pandas as pd
import numpy as np

#creating a series out of a list
fruits = ['orange', 'apple', 'mango', 'bananas']
fruits_categories = pd.Series(fruits)
print(fruits_categories)

#creating a series out of an np array
array_a = np.array([1,2,3,4,5])
array_series = pd.Series(array_a)
print(array_series)

0     orange
1      apple
2      mango
3    bananas
dtype: object
0    1
1    2
2    3
3    4
4    5
dtype: int64


In [ ]:
#creating custom indexes for pandas series
fruits = ['orange', 'apple', 'mango', 'bananas']
quantity = [10, 20, 30, 40]
fruits_categories = pd.Series(quantity, index=fruits)
print(fruits_categories)

orange     10
apple      20
mango      30
bananas    40
dtype: int64


In [ ]:
#Constructing a DataFrame from a dictionary of lists
data = {"ProductName": ["Product 1", "Product 2", "Product 3"], "ProductPrice": [10, 20, 30]}
df1 = pd.DataFrame(data, index=['A', 'B', 'C'])
print(df1)

  ProductName  ProductPrice
A   Product 1            10
B   Product 2            20
C   Product 3            30


In [ ]:
# Creating DataFrame from pd Series
product_name = pd.Series(["Product 1", "Product 2", "Product 3"])
product_price = pd.Series([10, 20, 30])
# Combine the Series into a dictionary
data = {"ProductName": product_name, "ProductPrice": product_price}
# Create the DataFrame from the dictionary
df = pd.DataFrame(data)
print(df)

  ProductName  ProductPrice
0   Product 1            10
1   Product 2            20
2   Product 3            30


In [ ]:
# Creating a DataFrame from a list
data = [['Product 1', 10], ['Product 2', 20], ['Product 3', 30]]
# Create DataFrame and specify column names
df = pd.DataFrame(data, columns=['ProductName', 'ProductPrice'])
print(df)

  ProductName  ProductPrice
0   Product 1            10
1   Product 2            20
2   Product 3            30


In [ ]:
# Creating a DataFrame efficiently
# Define the data as a dictionary with column names and values
data = {
    'ProductName': ['Product 1', 'Product 2', 'Product 3'],
    'ProductPrice': [10, 20, 30]
}

# Specify custom row labels
index = ['A', 'B', 'C']

# Create the DataFrame
df = pd.DataFrame(data, index=index)
print(df)

  ProductName  ProductPrice
A   Product 1            10
B   Product 2            20
C   Product 3            30


In [ ]:
# Create a list of products, 'Apple', 'Banana', 'Carrot', 'Daikon'.
# Convert the list into a pandas Series using the pd.Series() function.
# Print out the new Series to see the values.
# Create a Series with prices of the products, [2, 1, 3, 4]
# Print out the new Series to see the values.
# Add the two Series together and print out the result.
# Create a DataFrame using a dictionary of lists, where the keys are 'Product' and 'Price' and the values are the two Series you created.
# Print out the DataFrame to see the values.
# Create a DataFrame using a list of dictionaries, where each dictionary represents a row in the DataFrame with keys 'Product' and 'Price' and values from the two Series you created.
# Print out the DataFrame to see the values. Make sure to import pandas library before doing the exercises.

In [ ]:
import pandas as pd
products = ['Apple', 'Banana', 'Carrot', 'Daikon']
product_series = pd.Series(products)
print(product_series)

prices = pd.Series([2, 1, 3, 4])
print(prices)

#creating DataFrame from a dict
product_data = {
    'Product': product_series,
    'Price': prices
}
df = pd.DataFrame(product_data)
print(df)

#creating a DataFrame from a list
product_list = [
    {'Product': 'Apple', 'Price': 2},
    {'Product': 'Banana', 'Price': 1},
    {'Product': 'Carrot', 'Price': 3},
    {'Product': 'Daikon', 'Price': 4}
]
df1 = pd.DataFrame(product_list)
print(df1)

0     Apple
1    Banana
2    Carrot
3    Daikon
dtype: object
0    2
1    1
2    3
3    4
dtype: int64
  Product  Price
0   Apple      2
1  Banana      1
2  Carrot      3
3  Daikon      4
  Product  Price
0   Apple      2
1  Banana      1
2  Carrot      3
3  Daikon      4


In [ ]:
#loc and iloc in pandas DataFrame
df.index = ["Jack", "Thomas", "Alexandre", "Anne"]  # Setting custom row labels
selected_data = df.loc[["Jack", "Thomas"]]  # Selecting rows by label
print(selected_data)

selected_columns = df.iloc[:, 1:3]
print(selected_columns)

       Product  Price
Jack     Apple      2
Thomas  Banana      1
           Price
Jack           2
Thomas         1
Alexandre      3
Anne           4


In [ ]:
import numpy as np

array_3d = np.arange(6,42,2).reshape(2,3,3)
print(array_3d)

[[[ 6  8 10]
  [12 14 16]
  [18 20 22]]

 [[24 26 28]
  [30 32 34]
  [36 38 40]]]


Data Cleaning and Exploration with Pandas

In [ ]:
# 1.Identify the columns containing missing values.
# 2.Apply a method to handle the missing values
# 3.Check for duplicates and remove if any.
# 4.Remove any irrelevant columns.
# 1.Calculate summary statistics for numerical columns (mean, median, mode, etc).
# 2.Find the correlation between columns and create a heatmap.
# 3.Find the 3 most frequent countries that visitors tend to come from.
# 4.Determine the most common purpose of the visit by 'age_group'.
# 5.Analyse the data distribution of 'total_cost' column with respect to sevreal criteria : Country, age_group, purpose

In [ ]:
import pandas as pd

data = pd.read_csv('/content/VariableDefinitions.csv')
data.head()

Column Name                                         Definition
0            id                 Unique identifier for each tourist
1       country                The country a tourist coming  from.
2     age_group                        The age group of a tourist.
3   travel_with  The relation of people a tourist travel with t...
4  total_female                            Total number of females

Detecting Outliers

In [ ]:
#Using z-scores
import pandas as pd
import numpy as np
from scipy import stats

# Create a DataFrame with sample data
df = pd.DataFrame({'Height': [170, 160, 130, 190, 180, 150, 140, 200, 175, 165, 300]})

# Calculate the z-score of each data point
z_scores = np.abs(stats.zscore(df['Height']))
threshold = 3
outliers = df[z_scores > threshold]

print("Outliers based on z-score:")
print(outliers)

Outliers based on z-score:
Empty DataFrame
Columns: [Height]
Index: []


In [ ]:
#Using IQR
# Calculate Q1, Q3, and IQR
Q1 = df['Height'].quantile(0.25)
Q3 = df['Height'].quantile(0.75)
IQR = Q3 - Q1

# Define threshold and detect outliers
threshold = 1.5
outliers = df[(df['Height'] < (Q1 - threshold * IQR)) | (df['Height'] > (Q3 + threshold * IQR))]

print("Outliers based on IQR:")
print(outliers)

Outliers based on IQR:
    Height
10     300


Managing Outliers

In [ ]:
#Dropping outlers
# Assuming 'outliers' contains the indices of the outliers
df_clean = df.drop(outliers.index)
print("Cleaned DataFrame:")
print(df_clean)

Cleaned DataFrame:
   Height
0     170
1     160
2     130
3     190
4     180
5     150
6     140
7     200
8     175
9     165


In [ ]:
# Replace outliers with the median value of the dataset
median_value = df['Height'].median()
df.loc[df.index.isin(outliers.index), 'Height'] = median_value
print("DataFrame with replaced outliers:")
print(df)

DataFrame with replaced outliers:
    Height
0      170
1      160
2      130
3      190
4      180
5      150
6      140
7      200
8      175
9      165
10     170


Dictionary Mapping

In [ ]:
import pandas as pd
# Create a sample dataframe
df = pd.DataFrame({'Priority': ['Low', 'Medium', 'High', 'Medium', 'Low']})
# Define a mapping dictionary
priority_mapping = {'Low': 1, 'Medium': 2, 'High': 3}
# Use the replace function to apply the dictionary mapping
df['Priority_Encoded'] = df['Priority'].replace(priority_mapping)
# Display the updated dataframe
print(df)

  Priority  Priority_Encoded
0      Low                 1
1   Medium                 2
2     High                 3
3   Medium                 2
4      Low                 1


<ipython-input-25-1cbb2b532b23>:7: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Priority_Encoded'] = df['Priority'].replace(priority_mapping)


One-hot encoding

In [ ]:
import pandas as pd
# Create a sample dataframe with a categorical variable
df = pd.DataFrame({'Fruit': ['Apple', 'Orange', 'Banana', 'Banana', 'Orange', 'Apple']})
# Perform one-hot encoding
one_hot_df = pd.get_dummies(df, columns=['Fruit'])
# Display the encoded dataframe
print(one_hot_df)

   Fruit_Apple  Fruit_Banana  Fruit_Orange
0         True         False         False
1        False         False          True
2        False          True         False
3        False          True         False
4        False         False          True
5         True         False         False


Label Encoding

In [ ]:
from sklearn.preprocessing import LabelEncoder
# Sample data
data = ['apple', 'banana', 'banana', 'orange', 'kiwi', 'mango', 'apple']
# Create label encoder object
le = LabelEncoder()
# Fit and transform the data
encoded_data = le.fit_transform(data)
# Display the encoded data
print(encoded_data)

[0 1 1 4 2 3 0]


In [ ]:
file = open('text.txt', 'a')
content = file.write('\rHello')
file.close()
print(content)

6


In [ ]:
file = open('text.txt', 'r')
content = file.readlines()
file.close()
for line in content:
  print(line)

Hello WorldHello

Hello


In [ ]:
import csv

with open('data.csv', 'w', newline='') as file:
    writer = csv.writer(file)
    writer.writerow(['Name', 'Age', 'City'])
    writer.writerow(['Alice', 25, 'New York'])
    writer.writerow(['Bob', 30, 'San Francisco'])
    writer.writerow(['Charlie', 35, 'Los Angeles'])

In [ ]:
with open('data.csv', 'r') as file:
    reader = csv.reader(file)
    for row in reader:
        print(row)

['Name', 'Age', 'City']
['Alice', '25', 'New York']
['Bob', '30', 'San Francisco']
['Charlie', '35', 'Los Angeles']


In [ ]:
import pandas as pd

df = pd.read_csv('data.csv')
df

Name  Age           City
0    Alice   25       New York
1      Bob   30  San Francisco
2  Charlie   35    Los Angeles

In [ ]:
import json

data = {
  "name": "John Doe",
  "age": 30,
  "city": "New York"
}
with open('sample.json', 'w') as file:
  json.dump(data, file)

In [ ]:
with open('sample.json', 'r') as file:
  data = json.load(file)
print(data)

{'name': 'John Doe', 'age': 30, 'city': 'New York'}


In [ ]:
# Create a text file and write a short paragraph into it.
# Read the content of the file and print it.
# Append a new sentence to the existing file.
# Read a CSV file and display its contents.
# Write a program that stores a dictionary as a JSON file and then read

In [ ]:
text = 'Today is Monday, I so love Monday. Come home for dinner and I\'ll get you the best dishes around\n'
with open('sample.txt', 'w') as file:
  file.write(text)

In [ ]:
with open('sample.txt', 'r') as file:
  content = file.read()
print(content)

Today is Monday, I so love Monday. Come home for dinner and I'll get you the best dishes around
I'm glad you decidedx to come. Have a seat and I'll serve some food
I'm glad you decidedx to come. Have a seat and I'll serve some food
I'm glad you decided to come. Have a seat and I'll serve some food



In [ ]:
text2 = 'I\'m glad you decided to come. Have a seat and I\'ll serve some food\n'
with open('sample.txt', 'a') as file:
  file.write(text2)

In [ ]:
import csv

with open('sample.csv', 'w', newline='') as file:
  writer = csv.writer(file)
  writer.writerow(['Name', 'Age', 'City'])
  writer.writerow(['Alice', 25, 'New York'])
  writer.writerow(['Bob', 30, 'San Francisco'])
  writer.writerow(['Charlie', 35, 'Los Angeles'])

with open('sample.csv', 'r') as file:
  reader = csv.reader(file)
  for row in reader:
    print(row)

['Name', 'Age', 'City']
['Alice', '25', 'New York']
['Bob', '30', 'San Francisco']
['Charlie', '35', 'Los Angeles']


In [ ]:
import json

car = {'model': 'Toyota', 'year': 2022} # creates a dictionary
with open('sample.json', 'w') as file: #creates a json file in write mode
  json.dump(car, file) #json.dump is used to write into the json file

with open('sample.json', 'r') as file: #opens json file in read mode
   data = json.load(file) #loads the json file and saves the content into variable data
   print(json.dumps(data, indent=4))

{
    "model": "Toyota",
    "year": 2022
}


Ydata Profiling

In [ ]:
!pip install ydata-profiling

  Preparing metadata (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 393.5/393.5 kB 12.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 296.5/296.5 kB 11.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 687.8/687.8 kB 25.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 105.4/105.4 kB 6.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.2/43.2 kB 2.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.5/4.5 MB 60.8 MB/s eta 0:00:00
  Created wheel for htmlmin: filename=htmlmin-0.1.12-py3-none-any.whl size=27081 sha256=b1bb0dc697d97c28bde0b49e3e7c268aae5126885e7d97dd8ca07939e84e2b19
  Stored in directory: /root/.cache/pip/wheels/8d/55/1a/19cd535375ed1ede0c996405ebffe34b196d78e2d9545723a2
Successfully built htmlmin


In [ ]:
import pandas as pd
from ydata_profiling import ProfileReport

#creating a dataframe from csv
Popular_baby_names_df = pd.read_csv('/content/Popular_Baby_Names.txt')
Popular_baby_names_df.head()

Year of Birth  Gender                   Ethnicity Child's First Name  \
0           2011  FEMALE  ASIAN AND PACIFIC ISLANDER             SOPHIA   
1           2011  FEMALE  ASIAN AND PACIFIC ISLANDER              CHLOE   
2           2011  FEMALE  ASIAN AND PACIFIC ISLANDER              EMILY   
3           2011  FEMALE  ASIAN AND PACIFIC ISLANDER             OLIVIA   
4           2011  FEMALE  ASIAN AND PACIFIC ISLANDER               EMMA   

   Count  Rank  
0    119     1  
1    106     2  
2     93     3  
3     89     4  
4     75     5

In [ ]:
#Generating a Data Profile Report
profile = ProfileReport(Popular_baby_names_df, title='Popular Baby Names Report')

# Display the report
profile.to_notebook_iframe()

# Or generate an HTML report
profile.to_file("Popular_baby_names_report.html")

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [ ]:
!pip install requests pandas

In [ ]:
import requests as re
import pandas as pd

api_key = '4477fe45'
base_url = 'https://www.omdbapi.com/'
params = {
    'apikey': api_key,
    's': 'star wars'
}

results = re.get(base_url, params=params)

if results.status_code == 200:
  results = results.json()['Search']
else:
  print('Error: ', response.status_code)

movies_list = []


for result in results:
    movies_details = {
        "Title": result["Title"],
        "Year": result["Year"],
        "ID": result["imdbID"],
        "Type": result["Type"]
    }
    movies_list.append(movies_details)

movies_df = pd.DataFrame(movies_list)

movies_df.head()

Title  Year         ID   Type
0              Star Wars: Episode IV - A New Hope  1977  tt0076759  movie
1  Star Wars: Episode V - The Empire Strikes Back  1980  tt0080684  movie
2      Star Wars: Episode VI - Return of the Jedi  1983  tt0086190  movie
3      Star Wars: Episode VII - The Force Awakens  2015  tt2488496  movie
4       Star Wars: Episode I - The Phantom Menace  1999  tt0120915  movie

In [ ]:
import requests as re

result = re.get('https://www.nytimes.com/interactive/2017/06/23/opinion/trumps-lies.html')

In [ ]:
from bs4 import BeautifulSoup
soup = BeautifulSoup(result.text, 'html.parser')

In [ ]:
results = soup.find_all('span', attrs={'class': 'short-desc'})

In [ ]:
#Extracting the date
first_result = '2017 - ' + results[0].find('strong').text[:-1]
first_result

'2017 - Jan. 21'

In [ ]:
#Extracting the lie
first_result = results[0].contents[1][1:-2]
first_result

"I wasn't a fan of Iraq. I didn't want to go into Iraq."

In [ ]:
#Extracting the explanation
first_result = results[0].find('a').text[1:-1]
first_result

'He was for an invasion before he was against it.'

In [ ]:
#Extracting the URL
first_result = results[0].find('a')['href']
first_result

'https://www.buzzfeed.com/andrewkaczynski/in-2002-donald-trump-said-he-supported-invading-iraq-on-the'

In [ ]:
#Building a dataset
records = []
for result in results:
  date = result.find('strong').text[:-1] + ', 2017'
  lie = result.contents[1][1:-2]
  explanation = result.find('a').text[1:-1]
  url = result.find('a')['href']

  records.append((date, lie, explanation, url))

In [ ]:
#Applying a tabular data structure
import pandas as pd
df = pd.DataFrame(records, columns=['date', 'lie', 'explanation', 'url'])
df.head()

date                                                lie  \
0  Jan. 21, 2017  I wasn't a fan of Iraq. I didn't want to go in...   
1  Jan. 21, 2017  A reporter for Time magazine — and I have been...   
2  Jan. 23, 2017  Between 3 million and 5 million illegal votes ...   
3  Jan. 25, 2017  Now, the audience was the biggest ever. But th...   
4  Jan. 25, 2017  Take a look at the Pew reports (which show vot...   

                                         explanation  \
0   He was for an invasion before he was against it.   
1  Trump was on the cover 11 times and Nixon appe...   
2             There's no evidence of illegal voting.   
3  Official aerial photos show Obama's 2009 inaug...   
4            The report never mentioned voter fraud.   

                                                 url  
0  https://www.buzzfeed.com/andrewkaczynski/in-20...  
1  http://nation.time.com/2013/11/06/10-things-yo...  
2  https://www.nytimes.com/2017/01/23/us/politics...  
3  https://www.nytimes.com/2017/01/21/us/politics...  
4  https://www.nytimes.com/2017/01/24/us/politics...

In [ ]:
df['date'] = pd.to_datetime(df['date'],errors='coerce')

Web scraping

In [ ]:
import requests as re

url = 'https://quotes.toscrape.com/'

response = re.get(url)
print(response.text)

<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Quotes to Scrape</title>
    <link rel="stylesheet" href="/static/bootstrap.min.css">
    <link rel="stylesheet" href="/static/main.css">
    
    
</head>
<body>
    <div class="container">
        <div class="row header-box">
            <div class="col-md-8">
                <h1>
                    <a href="/" style="text-decoration: none">Quotes to Scrape</a>
                </h1>
            </div>
            <div class="col-md-4">
                <p>
                
                    <a href="/login">Login</a>
                
                </p>
            </div>
        </div>
    

<div class="row">
    <div class="col-md-8">

    <div class="quote" itemscope itemtype="http://schema.org/CreativeWork">
        <span class="text" itemprop="text">“The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.”</span>
        <span>by <small class="auth

In [ ]:
from bs4 import BeautifulSoup

soup = BeautifulSoup(response.text, 'html.parser')

quotes = soup.find_all('span', attrs={'class':'text'})
print(quotes)

[<span class="text" itemprop="text">“The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.”</span>, <span class="text" itemprop="text">“It is our choices, Harry, that show what we truly are, far more than our abilities.”</span>, <span class="text" itemprop="text">“There are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle.”</span>, <span class="text" itemprop="text">“The person, be it gentleman or lady, who has not pleasure in a good novel, must be intolerably stupid.”</span>, <span class="text" itemprop="text">“Imperfection is beauty, madness is genius and it's better to be absolutely ridiculous than absolutely boring.”</span>, <span class="text" itemprop="text">“Try not to become a man of success. Rather become a man of value.”</span>, <span class="text" itemprop="text">“It is better to be hated for what you are than to be loved for what you are not.”</spa